# Site settings
title: "Echo's Blog"
email: echohn@gmail.com
description: "Hi,I'm Echo Han."
baseurl: ""
url: "http://www.echoed.me"
username: "echohn"

filter: 'tag'


twitter: echo_hon
weibo: 1130234205
github: echohn

disqus_shortname: echohn

source: /Users/Echo/coding/documents/my_jekyll
destination: /Users/Echo/coding/documents/echohn.github.io

# Build settings
markdown: kramdown
permalink: pretty
sass:
  style: compressed

